#https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/creating-a-javascript-action
# this yml will be updated later; the intent is to create a javascript based pipeline to trigger tests

name: 'Trigger the server side unit tests'
description: 'This triggers the UTF tests of OutSystems via the exposed webservice and check the results'
inputs:
  target-url:  # url of the domain where the unit tests exist
    description: 'url of the domain where the unit tests exist'
    required: true
    default: 'https://myapp.outsystemscloud.com'
  outsystems-serviceuser-token:  # a service user is required in OutSystems. Provide the token that belongs to this user
    description: 'a service user is required in OutSystems. Provide the token that belongs to this user'
    required: true
    default: 'XYZ987&^%'
outputs:
  success: # id of output
    description: 'Boolean whether all tests succeeded or not'
runs:
  using: 'node12'
  main: 'runUnitTests.js'